Update support for engines variable in package.json for node version detection.
codesandbox/docs pull request #114
Opened 2023-01-23 12:30 UTC by JayaKrishnaNamburu

We recently added the ability on the pitcher to configure a VM's node version using `engines` filed in package.json. This is a npm standard field which is used to define the least version of node that a project needs. 

Till now, users can change a node version only through `environment.json` or `.nvmrc` files. If a project is already using a using `engines` filed in package.json they still need to create one of those files.  This latest change fixes it.

Here is the priority order for the detection

`.nvmrc` > `environment.json` > `package.json`

2023-01-24 07:38 UTC, christianalfoni requested changes
A small typo, but looks great 👍 Did we merge the feature yet? No matter, just wanted to point out not merging this until it is ready 😄

2023-01-24 07:38 UTC, christianalfoni commented on packages/projects-docs/pages/learn/environment/vm.md
> +If your package.json uses [engines](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) field then you need any `.nvmrc` or `environment.json` files.
```suggestion
If your package.json uses [engines](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) field then a `.nvmrc` or `environment.json` file is not needed. 
```

2023-01-24 08:52 UTC, JayaKrishnaNamburu commented
Yes, we deployed the change in pitcher. Bogdan suggested few improvements that we can look into. Added them to linear 👍

2023-01-25 07:58 UTC, christianalfoni approved these changes
Excellent! 👍 😄

2023-01-25 08:33 UTC, merged