Remove personal
codesandbox/docs pull request #204
Opened 2023-11-13 00:24 UTC by necoline

Remove reference to personal and add details about our transition period

2023-11-16 14:04 UTC, filipelima18 commented on packages/projects-docs/pages/learn/boxy/faqs.mdx
> +Boxy and all CodeSandbox AI-powered tools are available to Pro workspaces. You can [upgrade](https://codesandbox.io/pro) or [start a free trial](https://codesandbox.io/pro?team) to experience develop
```suggestion
Boxy and all CodeSandbox AI-powered tools are available to Pro workspaces. You can [upgrade](https://codesandbox.io/pro) or start a free trial to experience development with Boxy.
```
It doesn't look like the "Free trial" endpoint works anymore.

2023-11-16 16:10 UTC, filipelima18 commented on packages/projects-docs/pages/learn/plans/plan-overview.mdx
> +Additionally, you my invite others to join the workspace so that you can collaboration on sandboxes or repositories.
```suggestion
Additionally, you may invite others to join the workspace so that you can collaborate on sandboxes or repositories.
```

2023-11-16 16:11 UTC, filipelima18 commented on packages/projects-docs/pages/learn/plans/plan-overview.mdx
> +Pro offers unlimited collaboration, umlimited sandboxes and repositories (both private and public), higher VM specs and [much more](https://codesandbox.io/pricing).
```suggestion
Pro offers unlimited collaboration, unlimited sandboxes and repositories (both private and public), higher VM specs and [much more](https://codesandbox.io/pricing).
```

2023-11-16 16:26 UTC, filipelima18 commented on packages/projects-docs/pages/learn/plans/workspace.mdx
> +Just like in a Pro workspace, you may add members to the workspace by navigating to the workspace settings, and either sending an invite URL or entering an email address that will send off an invitat
```suggestion
Just like in a Pro workspace, you may add members to the workspace by navigating to the workspace settings, and either sending an invite URL or entering the email address of the member you wish to add (they will be notified by email).
```

2023-11-16 16:27 UTC, filipelima18 commented on packages/projects-docs/pages/learn/plans/workspace.mdx
> +Every workspace can now be upgraded. By selecting any action to upgrade from within a workspace, you will be able
Something missing here @necoline

2023-11-16 16:28 UTC, filipelima18 requested changes
Overall this looks great! I left some comments and suggestions and committed changes to fix an error and some typos @necoline.

2023-11-19 19:55 UTC, necoline commented on packages/projects-docs/pages/learn/plans/workspace.mdx
> +Every workspace can now be upgraded. By selecting any action to upgrade from within a workspace, you will be able
Thanks, I finished the sentence here

2023-11-21 13:42 UTC, filipelima18 approved these changes

2023-11-21 13:58 UTC, merged