chore: add Account Management FAQs
codesandbox/docs pull request #259
Opened 2024-07-12 15:41 UTC by filipelima18

Preview [here](https://nc93vh-3000.csb.app/faq). Closes PC-1953.

2024-07-15 08:27 UTC, necoline requested changes
Looks great! I made suggestions for two of the answers

2024-07-15 08:27 UTC, necoline commented on packages/projects-docs/pages/faq.mdx
> +You can leave or delete a workspace from the "Overview" tab of your [Workspace Settings](https://codesandbox.io/t/overview), by clicking on "Leave workspace", or "Delete workspace", respectively.
```suggestion
You can leave or delete a workspace from the "Overview" tab of your [Workspace Settings](https://codesandbox.io/t/overview), by clicking on "Leave workspace", or "Delete workspace", respectively.

There are some cases where leaving a workspace is not permitted.
1. You are the only workspace member with admin rights: Every workspace requires at least one admin member. Before you can leave the workspace, you must assign a new admin. 

2. You are trying to leave the only workspace connected to your account: Every account must be associated with at least one workspace. If you want to leave the only workspace connected to your account, you may create a new workspace and then leave the workspace you want to be disassociated with. Alternatively, deleting your account will remove you from any workspaces that you are a member of. 
```

2024-07-15 08:27 UTC, necoline commented on packages/projects-docs/pages/faq.mdx
> +Yes, you can upgrade or downgrade your plan at any time.
```suggestion
Yes, you can upgrade or downgrade your plan at any time from the settings page. 

```

2024-07-16 11:53 UTC, filipelima18 commented
Thanks for the suggestions @necoline! Committed & ready for review

2024-07-16 13:48 UTC, necoline approved these changes

2024-07-16 14:24 UTC, merged